# Generated by Django 4.2.7 on 2023-12-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name_uz', models.CharField(max_length=50, verbose_name='Fan nomi')),
                ('subject_name_en', models.CharField(max_length=50, verbose_name='Subject name')),
                ('subject_name_ru', models.CharField(max_length=50, verbose_name='Урок имя')),
                ('theme_title_uz', models.CharField(max_length=255, verbose_name='Mavzu sarlavhasi')),
                ('theme_title_en', models.CharField(max_length=255, verbose_name='Theme title')),
                ('theme_title_ru', models.CharField(max_length=255, verbose_name='Название темы')),
                ('subject_start_time', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('subject_end_time', models.DateTimeField(verbose_name='Tugash vaqti')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
    ]
