# Generated by Django 4.2.7 on 2023-12-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_piar', '0006_videolinks_videogallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_field',
        ),
    ]
