# Generated by Django 4.2.8 on 2023-12-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0004_alter_documents_doc_org_alter_documents_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='doc_org',
            field=models.CharField(choices=[('2', 'Prezident'), ('3', 'Vazirlar mahkamasi'), ('4', 'Xalq talimi vazirligi'), ('1', 'Parlament'), ('5', 'Boshqarma')], max_length=25, verbose_name='Tashkilot/Organisation'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='doc_type',
            field=models.CharField(choices=[('1', 'Qonun'), ('2', 'Qaror'), ('4', 'Buyruq'), ('5', 'Farmon'), ('3', 'Farmoyish')], max_length=15, verbose_name='Toifa/Type'),
        ),
    ]
